### ISSUE TITLE
dynamically retrieve secret contract address

### ISSUE THREAD

**Issue by nionis** [nionis/enigma-benchmarking#2]
Find out if there is a place where we can find the secret contract address other than the one within tests.
Currently it feels a bit hacky but acceptable I suppose for mainnet since the address doesn't change.
[src](https://github.com/nionis/enigma-benchmarking/blob/master/client/src/models/Enigma.ts#L49)

**Comment by ainsleys** [comment]
Hey @nionis -- opening up an issue for this internally. More soon!
